Update project to use juggler@3
strongloop/loopback-sdk-ios-codegen pull request #10
Opened 2016-09-23 20:59 UTC by gunjpan

Update package.json to use
loopback-datasource-juggler@3.x

2016-10-14 13:22 UTC, bajtos requested changes

2016-10-14 13:22 UTC, bajtos commented on package.json
> +    "loopback-datasource-juggler": "^3.0.0",
I am afraid you are changing a wrong place. You should remove this line entirely and use `loopback: '^3.0.0'` instead, see L42.

2016-10-14 19:01 UTC, gunjpan commented on package.json
> +    "loopback-datasource-juggler": "^3.0.0",
@bajtos : Yes, I noticed that and corrected it on Local. But facing failures, trying to resolve them and didn't push yet.

2016-11-22 15:14 UTC, bajtos commented
@gunjpan ping, what's the status of this pull request?

2016-11-22 15:26 UTC, gunjpan commented
@bajtos : No progress ATM as focused on getting `geopoint` out of the door. It's committed for this sprint, aiming to start on it today/tomorrow earliest.

2016-12-01 15:34 UTC, bajtos commented
I think this should be re-assigned to @strongloop/squad-apex ?

2016-12-01 15:45 UTC, gunjpan commented
@bajtos : I've committed to working on completing it this sprint. No need to reassign. Thanks.

2020-05-15 09:52 UTC, closed without merging